// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelicarioApplication.Data;

namespace RelicarioApplication.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230412015406_NxN")]
    partial class NxN
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlunoModelAtividadesModel", b =>
                {
                    b.Property<int>("AlunosId")
                        .HasColumnType("int");

                    b.Property<int>("AtvPraticanteId")
                        .HasColumnType("int");

                    b.HasKey("AlunosId", "AtvPraticanteId");

                    b.HasIndex("AtvPraticanteId");

                    b.ToTable("AlunoModelAtividadesModel");
                });

            modelBuilder.Entity("RelicarioApplication.Models.AlunoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("NomeAluno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TB_ALUNOS");
                });

            modelBuilder.Entity("RelicarioApplication.Models.AtividadesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeAtividade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessorResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TB_ATIVIDADES");
                });

            modelBuilder.Entity("AlunoModelAtividadesModel", b =>
                {
                    b.HasOne("RelicarioApplication.Models.AlunoModel", null)
                        .WithMany()
                        .HasForeignKey("AlunosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelicarioApplication.Models.AtividadesModel", null)
                        .WithMany()
                        .HasForeignKey("AtvPraticanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
